### ISSUE TITLE
Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated. [[{{node PyFunc}}]]

### ISSUE THREAD

**Issue by ayush431** [limkhashing/ID-Document-Image-Classification#1]
Getting this error while training the model after few epochs ??
can you tell me how overcome to this problem ?

**Comment by ayush431** [comment]
Getting this error while training the model after few epochs ??
can you tell me how overcome this problem ?

**Comment by limkhashing** [comment]
You can google error and try the solutions 
https://stackoverflow.com/questions/62943048/unable-to-solve-error-occurred-when-finalizing-generatordataset-iterator-faile

I never faced this error before during my training
